version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: diplom-postgres
    ports:
      - "7891:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diplom
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: