version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: diplom-postgres
    ports:
      - "7891:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: diplom
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: diplom-backend
    ports:
      - "3003:3003"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=diplom
    restart: unless-stopped

volumes:
  postgres_data:
